/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reutilisable;

import dev.lurcat.ppe3.Interface.Catalogue;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;


/**
 *
 * @author a.masvidal
 */
public class CardProduit extends javax.swing.JPanel {

    private int idProduit, idCategorie, stock;
    private String libelle, description, lienImage;
    private double tarif;
    private float note;
    private ArrayList<String> produit;
    private Catalogue index;
    
    
    /**
     * Creates new form CardProduit
     */
    public CardProduit() {
        initComponents();
        jButtonAjoutPanier.setIcon(new ImageIcon(new ImageIcon("G:\\COURS\\NetBeansProjects\\PPE3\\Icones/icons8-ajouter-au-panier-64.png").getImage().getScaledInstance(20, 20, Image.SCALE_SMOOTH)));
    }
    
    /**
     * Set tous les attributs de la classe
     * @param pUnProduit 
     * @param pIndex 
     */
    public void setteur(ArrayList pUnProduit, Catalogue pIndex){
        this.idProduit = Integer.parseInt((String) pUnProduit.get(0));
        this.libelle = (String) pUnProduit.get(1);
        this.description = (String) pUnProduit.get(2);
        this.tarif = Double.parseDouble((String) pUnProduit.get(3));
        this.stock = Integer.parseInt((String) pUnProduit.get(4));
        this.note = Float.parseFloat((String) pUnProduit.get(5));
        this.lienImage = (String) pUnProduit.get(6);
        this.idCategorie = Integer.parseInt((String) pUnProduit.get(7));
        this.produit = pUnProduit;
        this.index = pIndex;
    }
    
    /**
     * remplie les champs de la card produit avec les données d'un produit ainsi que les attributs de la class
     * 
     */
    public void remplissage(){
            
            jTextAreaTitre.setText(String.valueOf(this.libelle));
            jTextAreaDescription.setText(String.valueOf(this.description));
            jLabelTarif.setText(String.valueOf(String.valueOf(this.tarif) + " €"));
            jLabelNote.setText(String.valueOf(String.valueOf(this.note) + "/10"));
            
        try {
            String monFichierImage = String.valueOf(this.lienImage);
            BufferedImage myPicture = ImageIO.read(new File(monFichierImage));
            ImageIcon image = new ImageIcon(new ImageIcon(myPicture).getImage().getScaledInstance(200, 112, Image.SCALE_DEFAULT));
            jLabelImage.setIcon(image);
        } catch (IOException ex) {
            Logger.getLogger(CardProduit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImage = new javax.swing.JLabel();
        jLabelTarif = new javax.swing.JLabel();
        jLabelNote = new javax.swing.JLabel();
        jTextAreaDescription = new javax.swing.JTextArea();
        jTextAreaTitre = new javax.swing.JTextArea();
        jButtonAjoutPanier = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 236, 236), 1, true));
        setMaximumSize(new java.awt.Dimension(180, 96));
        setMinimumSize(new java.awt.Dimension(180, 96));
        setPreferredSize(new java.awt.Dimension(215, 350));

        jLabelImage.setMaximumSize(new java.awt.Dimension(180, 96));
        jLabelImage.setMinimumSize(new java.awt.Dimension(180, 96));
        jLabelImage.setPreferredSize(new java.awt.Dimension(200, 112));

        jLabelTarif.setText("none");

        jLabelNote.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNote.setText("none");

        jTextAreaDescription.setEditable(false);
        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setLineWrap(true);
        jTextAreaDescription.setRows(5);
        jTextAreaDescription.setWrapStyleWord(true);
        jTextAreaDescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(172, 172, 172)));
        jTextAreaDescription.setMaximumSize(new java.awt.Dimension(180, 2147483647));
        jTextAreaDescription.setMinimumSize(new java.awt.Dimension(180, 96));
        jTextAreaDescription.setOpaque(false);
        jTextAreaDescription.setPreferredSize(new java.awt.Dimension(190, 82));

        jTextAreaTitre.setEditable(false);
        jTextAreaTitre.setColumns(20);
        jTextAreaTitre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextAreaTitre.setLineWrap(true);
        jTextAreaTitre.setRows(5);
        jTextAreaTitre.setWrapStyleWord(true);
        jTextAreaTitre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(172, 172, 172)));
        jTextAreaTitre.setPreferredSize(new java.awt.Dimension(242, 40));

        jButtonAjoutPanier.setPreferredSize(new java.awt.Dimension(30, 30));
        jButtonAjoutPanier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAjoutPanierMouseClicked(evt);
            }
        });
        jButtonAjoutPanier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjoutPanierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelImage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(jTextAreaTitre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextAreaDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAjoutPanier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextAreaTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextAreaDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNote, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTarif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAjoutPanier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAjoutPanierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjoutPanierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAjoutPanierActionPerformed

    private void jButtonAjoutPanierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAjoutPanierMouseClicked
        try {
            this.index.addProduitPanier(index, this.idProduit, this.stock);
        } catch (SQLException ex) {
            Logger.getLogger(CardProduit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAjoutPanierMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjoutPanier;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelNote;
    private javax.swing.JLabel jLabelTarif;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextArea jTextAreaTitre;
    // End of variables declaration//GEN-END:variables
}
